[theme]
primaryColor = "#2962ff"
backgroundColor = "#131722"
secondaryBackgroundColor = "#1e222d"
textColor = "#d1d4dc"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
